### PR TITLE
Support version active lts or latest

### PR DESCRIPTION
**Pull request by segayuu**
- update eslint
- update eslint-config-hexo
- define engines field
- fix lint error

### CODE REVIEW

**Comment by segayuu** [comment]
https://travis-ci.com/segayuu/hexo-generator-archive/jobs/160470115#L451
nunjacks not supported node@11.2

**Comment by JLHwung** [comment]
> nunjacks not supported node@11.2

The issue was raised to https://github.com/mozilla/nunjucks/issues/1168

**Comment by tomap** [comment]
Maybe you should stick to node 10 so that we are not blocked by mozilla/nunjucks being late with updates

**Review by tomap — APPROVED** [review]
LGTM but i'm not sure why you did not simply use node >= 6.9

**Comment by segayuu** [comment]
@tomap The reason not to define> = 6.9 is to clarify that we do not support 7 and 9 which have already ended support.

**Comment by segayuu** [comment]
https://github.com/hexojs/site/issues/798#issuecomment-435408912
A ci error could be avoided by the same method as this comment.
However, it means that we can not do ci automatic test in the latest version.

**Review by tomap — APPROVED** [review]

**Pull request merged**
