### PR TITLE
release: 1.0.0

### PR DESCRIPTION
**Pull request by curbengh**

### CODE REVIEW

**Comment by tomap** [comment]
We need to realease hexo-pagination 1.0.0 before those one. Andthere is also an update of eslint config plugin to do, once released

**Comment by curbengh** [comment]
Good catch on hexo-pagination.

Edit: Pending ~~https://github.com/hexojs/hexo-pagination/pull/19~~

https://www.npmjs.com/package/hexo-pagination/v/1.0.0

**Comment by curbengh** [comment]
We'll wait for dependabot to update hexo-pagination in this repo, due to use of package-lock.

https://github.com/hexojs/hexo-generator-archive/pull/59 merged

@tomap This PR is ready.

**Review by SukkaW — APPROVED** [review]

**Comment by tomap** [comment]
publication done

**Pull request merged**
